name: Update rosdistro cache

# Controls when the action will run.
on:
  push:
    branches: ['main']
    paths: ['**.yaml']

# Cancel in-progress runs when a new workflow with the same group name is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@v0.7 # Use the latest version or a specific one
      with:
        target-ros2-distro: jazzy

    - name: Run the generate-cache.sh script
      run: ./scripts/generate-cache.sh

    - name: Commit files
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add ./rosdistro_cache
        git commit -m "Update caches"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
